backend:
  name: git-gateway
  branch: master
media_folder: "_assets/img"
media_folder: "_assets/img"
collections:
  - name: "sections"
    label: "Sections"
    delete: true
    create: true
    preview_path: "/"
    slug: "{{slug}}"
    fields:
      - {label: "Page Class", name: "pageClass", widget: "string", default: "section"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image", required: false}
      - {label: "Image alt", name: "alt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}